
project_id = "kurpshcdafxbyqnzxvxu"

[cors]
allow_origin = ["*"]
allow_methods = ["GET", "POST", "OPTIONS", "PUT", "DELETE"]
allow_headers = ["authorization", "x-client-info", "apikey", "content-type", "range"]
allow_credentials = false
max_age = 86400
