
project_id = "kurpshcdafxbyqnzxvxu"

[cors]
allow_origin = ["*"]
allow_methods = ["GET", "POST", "OPTIONS", "PUT", "DELETE"]
allow_headers = ["*"]
allow_credentials = true
max_age = 86400

[global.config]
APP_URL = "https://workshop.lovable.dev"
MERCADOPAGO_ACCESS_TOKEN = "APP_USR-609050106721186-021911-eae43656d661dca581ec088d09694fd5-2268930884"
MERCADOPAGO_PUBLIC_KEY = "APP_USR-711c6c25-bab3-4517-8ecf-c258c5ee4691"
