
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Substitua estas credenciais pelas do seu novo projeto
const SUPABASE_URL = "https://SEU_NOVO_ID_PROJETO.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "SUA_NOVA_CHAVE_PUBLICA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
