// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwdqdxlgfourpztdzvvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3ZHFkeGxnZm91cnB6dGR6dnZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3ODE3NjUsImV4cCI6MjA1NzM1Nzc2NX0.d_hIExFVXsIVXB3A-MumkkZB5DvB0dKXP5PEIRTn3Sg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);