// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gflhpcvldqoqjikeepjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmbGhwY3ZsZHFvcWppa2VlcGpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4NDU1NTcsImV4cCI6MjA0OTQyMTU1N30.s-P_hGjoBf8nUTx7LLCxSWW07fOSrV5qw_2Krj373YQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);